<?php

namespace App\Utils;

use App\Enums\ClauseEnum;

class CodeTypeUtils
{
  public static function toCodeID($type)
  {
    switch ($type->code) {
      case ClauseEnum::C1->code():
        return ClauseEnum::C1->value;
      case ClauseEnum::C2->code():
        return ClauseEnum::C2->value;
      case ClauseEnum::C3->code():
        return ClauseEnum::C3->value;
      case ClauseEnum::CH1->code():
        return ClauseEnum::CH1->value;
      case ClauseEnum::CH2->code():
        return ClauseEnum::CH2->value;
      case ClauseEnum::C1P->code():
        return ClauseEnum::C1P->value;
      case ClauseEnum::C2P->code():
        return ClauseEnum::C2P->value;
      case ClauseEnum::C3P->code():
        return ClauseEnum::C3P->value;
      case ClauseEnum::CH4->code():
        return ClauseEnum::CH4->value;
      case ClauseEnum::CH3->code():
        return ClauseEnum::CH3->value;
      case ClauseEnum::C10->code():
        return ClauseEnum::C10->value;
      case ClauseEnum::C11->code():
        return ClauseEnum::C11->value;
      case ClauseEnum::C11B->code():
        return ClauseEnum::C11B->value;
      case ClauseEnum::C11C->code():
        return ClauseEnum::C11C->value;
      case ClauseEnum::C45T->code():
        return ClauseEnum::C45T->value;
      case ClauseEnum::C12->code():
        return ClauseEnum::C12->value;
      case ClauseEnum::C13->code():
        return ClauseEnum::C13->value;
      case ClauseEnum::C44T->code():
        return ClauseEnum::C44T->value;
      case ClauseEnum::C14->code():
        return ClauseEnum::C14->value;
      case ClauseEnum::C15->code():
        return ClauseEnum::C15->value;
      case ClauseEnum::C43T->code():
        return ClauseEnum::C43T->value;
      case ClauseEnum::CH5->code():
        return ClauseEnum::CH5->value;
      case ClauseEnum::CH6->code():
        return ClauseEnum::CH6->value;
      case ClauseEnum::CH7->code():
        return ClauseEnum::CH7->value;
      case ClauseEnum::CH8->code():
        return ClauseEnum::CH8->value;
      case ClauseEnum::C30->code():
        return ClauseEnum::C30->value;
      case ClauseEnum::C29D->code():
        return ClauseEnum::C29D->value;
      case ClauseEnum::C28M->code():
        return ClauseEnum::C28M->value;
      case ClauseEnum::CH13->code():
        return ClauseEnum::CH13->value;
      case ClauseEnum::CH12->code():
        return ClauseEnum::CH12->value;
      case ClauseEnum::C43->code():
        return ClauseEnum::C43->value;
      case ClauseEnum::C43M->code():
        return ClauseEnum::C43M->value;
      case ClauseEnum::CH15->code():
        return ClauseEnum::CH15->value;
      case ClauseEnum::CH14->code():
        return ClauseEnum::CH14->value;
      case ClauseEnum::C8->code():
        return ClauseEnum::C8->value;
      case ClauseEnum::C7->code():
        return ClauseEnum::C7->value;
      case ClauseEnum::C6->code():
        return ClauseEnum::C6->value;
      case ClauseEnum::CH11->code():
        return ClauseEnum::CH11->value;
      case ClauseEnum::CH10->code():
        return ClauseEnum::CH10->value;
      case ClauseEnum::C44D->code():
        return ClauseEnum::C44D->value;
      case ClauseEnum::C44S->code():
        return ClauseEnum::C44S->value;
      case ClauseEnum::C45D->code():
        return ClauseEnum::C45D->value;
      case ClauseEnum::C45S->code():
        return ClauseEnum::C45S->value;
      case ClauseEnum::C46D->code():
        return ClauseEnum::C46D->value;
      case ClauseEnum::C46S->code():
        return ClauseEnum::C46S->value;
      case ClauseEnum::C47D->code():
        return ClauseEnum::C47D->value;
      case ClauseEnum::C47S->code():
        return ClauseEnum::C47S->value;
      case ClauseEnum::C48D->code():
        return ClauseEnum::C48D->value;
      case ClauseEnum::C48S->code():
        return ClauseEnum::C48S->value;
      case ClauseEnum::C99->code():
        return ClauseEnum::C99->value;
      case ClauseEnum::C99S->code():
        return ClauseEnum::C99S->value;
      case ClauseEnum::C99D->code():
        return ClauseEnum::C99D->value;
      case ClauseEnum::C99M->code():
        return ClauseEnum::C99M->value;
      case ClauseEnum::CA1->code():
        return ClauseEnum::CA1->value;
      case ClauseEnum::CA2->code():
        return ClauseEnum::CA2->value;
      case ClauseEnum::CA5->code():
        return ClauseEnum::CA5->value;
      case ClauseEnum::CA6->code():
        return ClauseEnum::CA6->value;
      case ClauseEnum::CA7->code():
        return ClauseEnum::CA7->value;
      case ClauseEnum::CA8->code():
        return ClauseEnum::CA8->value;
      case ClauseEnum::CA9->code():
        return ClauseEnum::CA9->value;
      case ClauseEnum::CA10->code():
        return ClauseEnum::CA10->value;
      case ClauseEnum::CA11->code():
        return ClauseEnum::CA11->value;
      case ClauseEnum::CA12->code():
        return ClauseEnum::CA12->value;
      case ClauseEnum::CA13->code():
        return ClauseEnum::CA13->value;
      case ClauseEnum::CA25->code():
        return ClauseEnum::CA25->value;
      case ClauseEnum::CA26->code():
        return ClauseEnum::CA26->value;
      case ClauseEnum::CA27->code():
        return ClauseEnum::CA27->value;
      case ClauseEnum::CA28->code():
        return ClauseEnum::CA28->value;
      case ClauseEnum::CA14->code():
        return ClauseEnum::CA14->value;
      case ClauseEnum::CA15->code():
        return ClauseEnum::CA15->value;
      case ClauseEnum::CA16->code():
        return ClauseEnum::CA16->value;
      case ClauseEnum::C31->code():
        return ClauseEnum::C31->value;
      case ClauseEnum::C32->code():
        return ClauseEnum::C32->value;
      case ClauseEnum::C35->code():
        return ClauseEnum::C35->value;
      case ClauseEnum::C36->code():
        return ClauseEnum::C36->value;
      case ClauseEnum::C70A->code():
        return ClauseEnum::C70A->value;
      case ClauseEnum::C81->code():
        return ClauseEnum::C81->value;
      case ClauseEnum::C81A->code():
        return ClauseEnum::C81A->value;
      case ClauseEnum::C87->code():
        return ClauseEnum::C87->value;
      case ClauseEnum::C89->code():
        return ClauseEnum::C89->value;
      case ClauseEnum::C89A->code():
        return ClauseEnum::C89A->value;
      case ClauseEnum::C90->code():
        return ClauseEnum::C90->value;
      case ClauseEnum::C91->code():
        return ClauseEnum::C91->value;
      case ClauseEnum::C94->code():
        return ClauseEnum::C94->value;
      case ClauseEnum::C95->code():
        return ClauseEnum::C95->value;
      case ClauseEnum::CVA1->code():
        return ClauseEnum::CVA1->value;
      case ClauseEnum::CVR1->code():
        return ClauseEnum::CVR1->value;
      case ClauseEnum::CV11->code():
        return ClauseEnum::CV11->value;
      case ClauseEnum::CC01->code():
        return ClauseEnum::CC01->value;
      case ClauseEnum::CC02->code():
        return ClauseEnum::CC02->value;
      case ClauseEnum::CC03->code():
        return ClauseEnum::CC03->value;
      case ClauseEnum::CC04->code():
        return ClauseEnum::CC04->value;
      case ClauseEnum::CC05->code():
        return ClauseEnum::CC05->value;
      case ClauseEnum::CC06->code():
        return ClauseEnum::CC06->value;
    }
  }
}
